//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amcs_scanner_app.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amcs_scanner_app.Resources.Localization.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Zwischenspeicher.
        /// </summary>
        internal static string Cached {
            get {
                return ResourceManager.GetString("Cached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommission.
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelöscht.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die aktuelle Kommission beenden?.
        /// </summary>
        internal static string EndCommission {
            get {
                return ResourceManager.GetString("EndCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung fehlgeschlagen.
        /// </summary>
        internal static string FailedToAuthenticate {
            get {
                return ResourceManager.GetString("FailedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschluss.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossen.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor.
        /// </summary>
        internal static string Gate {
            get {
                return ResourceManager.GetString("Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wareneingang.
        /// </summary>
        internal static string IncomingGoods {
            get {
                return ResourceManager.GetString("IncomingGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhaft.
        /// </summary>
        internal static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventur.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesperrt.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet mit Kennummer:.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie ihre Kennzahl ein.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Lagerverwaltung.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Mehr als ein Barcode erkannt!.
        /// </summary>
        internal static string MoreThanOneCodeScanned {
            get {
                return ResourceManager.GetString("MoreThanOneCodeScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrfachauswahl.
        /// </summary>
        internal static string MultipleSelection {
            get {
                return ResourceManager.GetString("MultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Barcode erkannt.
        /// </summary>
        internal static string NoBarcodesParsed {
            get {
                return ResourceManager.GetString("NoBarcodesParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es besteht aktuell keine Verbindung zum System.
        /// </summary>
        internal static string NoConnectionToSystem {
            get {
                return ResourceManager.GetString("NoConnectionToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden noch nicht alle Positionen bearbeitet! Nach Beendigung können diese nicht mehr bearbeitet werden..
        /// </summary>
        internal static string NotAllPositionsDone {
            get {
                return ResourceManager.GetString("NotAllPositionsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Keine Benutzerkennung angegeben.
        /// </summary>
        internal static string NoUserGiven {
            get {
                return ResourceManager.GetString("NoUserGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oder scannen sie ihren Barcode.
        /// </summary>
        internal static string OrScan {
            get {
                return ResourceManager.GetString("OrScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parken.
        /// </summary>
        internal static string Park {
            get {
                return ResourceManager.GetString("Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die aktuelle Kommission Pausieren?.
        /// </summary>
        internal static string PauseCommission {
            get {
                return ResourceManager.GetString("PauseCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterbrochen.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählte Aufträge.
        /// </summary>
        internal static string PickedOrders {
            get {
                return ResourceManager.GetString("PickedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stück.
        /// </summary>
        internal static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positionen.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeholt.
        /// </summary>
        internal static string Retrieved {
            get {
                return ResourceManager.GetString("Retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuellen Benutzer auf dem Gerät speichern.
        /// </summary>
        internal static string SaveCurrentUser {
            get {
                return ResourceManager.GetString("SaveCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Kein Auftrag!.
        /// </summary>
        internal static string ScannedCodeWasNoOrder {
            get {
                return ResourceManager.GetString("ScannedCodeWasNoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Keine Benutzerkennung.
        /// </summary>
        internal static string ScannedCodeWasNoUser {
            get {
                return ResourceManager.GetString("ScannedCodeWasNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Der Auftrag ist nicht in der Liste!.
        /// </summary>
        internal static string ScannedOrderNotInList {
            get {
                return ResourceManager.GetString("ScannedOrderNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begonnen.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet bleiben.
        /// </summary>
        internal static string StayLoggedIn {
            get {
                return ResourceManager.GetString("StayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem System wurden noch nicht alle Positionen gemeldet. Eine Verbindung zum Netzwerk wird zum abschließen benötigt!.
        /// </summary>
        internal static string StillGotCachedItems {
            get {
                return ResourceManager.GetString("StillGotCachedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerplätze.
        /// </summary>
        internal static string Storages {
            get {
                return ResourceManager.GetString("Storages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ist gespeichert.
        /// </summary>
        internal static string UserIsSaved {
            get {
                return ResourceManager.GetString("UserIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum Netzwerk wird benötigt.
        /// </summary>
        internal static string WaitingForCacheCleared {
            get {
                return ResourceManager.GetString("WaitingForCacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerhaltung.
        /// </summary>
        internal static string Warehousing {
            get {
                return ResourceManager.GetString("Warehousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewicht.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
